#!/usr/bin/env ruby

begin
  require "willow_camp_cli"
rescue LoadError
  # Try to load from the local path if the gem is not found
  lib_path = File.expand_path("../../lib", __FILE__)
  $LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)
  require "willow_camp_cli"
end

WillowCampCLI::CLI.run(ARGV)
